#!/usr/bin/bash

GITHUB_USERNAME=Sheriefalgalaly
GITHUB_TOKEN=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
REPO_NAME=Embedded_linux

REPO_URL="https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${GITHUB_USERNAME}/${REPO_NAME}.git"
git init 

git add .
com="$1"
git commit -m "$com"
git branch -M main
git remote add origin https://github.com/Sheriefalgalaly/Embedded_linux.git

expect -c "
spawn git push -u origin main
expect \"Username for 'https://github.com': \"
send \"$GITHUB_USERNAME\r\"
expect \"Password for 'https://github.com': \"
send \"$GITHUB_TOKEN\n\"
interact
"


