#!/usr/bin/bash

GITHUB_USERNAME=Sheriefalgalaly
GITHUB_TOKEN=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
REPO_NAME=Embedded_linux

REPO_URL="https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${GITHUB_USERNAME}/${REPO_NAME}.git"
git init 

git add .
com="$1"
git commit -m "$com"

git remote add origin https://github.com/Sheriefalgalaly/Embedded_linux.git
git branch -M main

expect -c "
spawn git push -u origin main
expect \"Username for 'https://github.com': \"
send \"$GITHUB_USERNAME\r\"
expect \"Password for 'https://github.com': \"
send \"$GITHUB_TOKEN\r\"
interact
"


